version: "3.7"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1111PPpp
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - dayularnet

  my-app:
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - dayularnet
networks:
  dayularnet:
    driver: bridge